### ISSUE TITLE
Ghunt login issue

### ISSUE THREAD

**Issue by Suzy1992** [mxrch/GHunt#479] opened 2024-01-10 10:32 UTC
I am not able to login into Ghunt, Everytime I try it says cookies invalid. I have tried on multiple systems and only one account is logged in on Firefox. Can someone help me on this..
@mxrch @ghunt @esidate

GHunt is listening on port 60067...
[+] Received cookies !

[-] Seems like the cookies are invalid, try regenerating them.

**Comment by esidate** [comment] 2024-01-10 14:05
Hi @Suzy1992 try logging out your Gmail account and log in again

**Comment by w0dxDev** [comment] 2024-01-10 19:34
Fok

**Comment by shion1305** [comment] 2024-01-10 21:01
https://github.com/mxrch/GHunt/issues/476#issuecomment-1885723506

**Comment by mxrch** [comment] 2024-01-11 19:32
Effectively, duplicate of https://github.com/mxrch/GHunt/issues/476, thanks @shion1305.

**Closed by mxrch** 2024-01-11 19:32 UTC
