### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'encode'

### ISSUE THREAD

**Issue by richdev135** [mxrch/GHunt#187] opened 2021-01-03 14:11 UTC
I am using Python 3.8.5. 

Cookies were verified correct by check_and_gen.py

Chrome Version 87.0.4280.66 (Official Build) (64-bit)

Traceback (most recent call last):
  File "hunt.py", line 50, in <module>
    data = is_email_google_account(client, auth, cookies, email,
  File "/home/rich/dev/GHunt-master/lib/utils.py", line 42, in is_email_google_account
    req = httpx_client.post(host + url, data=body.format(email), headers=headers, cookies=cookies)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 992, in post
    return self.request(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 722, in request
    request = self.build_request(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 307, in build_request
    headers = self._merge_headers(headers)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 356, in _merge_headers
    merged_headers.update(headers)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_models.py", line 680, in update
    headers = Headers(headers)
  File "/usr/local/lib/python3.8/dist-packages/httpx/_models.py", line 551, in __init__
    self._list = [
  File "/usr/local/lib/python3.8/dist-packages/httpx/_models.py", line 555, in <listcomp>
    normalize_header_value(v, encoding),
  File "/usr/local/lib/python3.8/dist-packages/httpx/_utils.py", line 56, in normalize_header_value
    return value.encode(encoding or "ascii")
AttributeError: 'NoneType' object has no attribute 'encode'

What more info can I give you?  

Thanks!

**Comment by luisfelipesdn12** [comment] 2021-01-03 14:18
I'm having the exactly same issue :/

**Comment by luisfelipesdn12** [comment] 2021-01-03 14:19
I think this is a duplicate of #186

**Comment by mxrch** [comment] 2021-01-03 14:38
Yes this is a duplicate of #186, do a git pull, a pip install -r requirements.txt and relaunch the check_and_gen.py.

**Closed by mxrch** 2021-01-03 14:38 UTC
