### ISSUE TITLE
indexError with cookies thing

### ISSUE THREAD

**Issue by fluxis1** [mxrch/GHunt#332] opened 2022-04-23 16:39 UTC
**Describe the bug**
Did everything perfectly and yet it says "IndexError: list index out of range" When i tried both the listening method and base64 method.. Both of those said indexerror.. But what i noticed when doing the manual (3rd method) is that im missing LSID. This is probably because i did the inspect > application > storage > myaccountgoogle > cookies way. This is proably why but the thing is i did the other method which is the network thingy but it doesnt show the 302 GET.. only shows 200 with the myaccountgoogle thingy.

**Expected behavior**
For the check and gen py and everything to work. Where the VALID cookies actually doesnt give back a indexing error when using check_and_gen.py

**Screenshots**
![164873676-65294c4b-3175-4b2a-84cb-8f2580033c30](https://user-images.githubusercontent.com/104270349/164915132-229bbae3-3ef8-4423-a7ab-db33a46a1059.png)

**System (please complete the following information):**
 - OS: Windows 10 21h1 HOME
 - Python version : 3.10

**Additional context**
none

**Comment by mxrch** [comment] 2022-06-04 10:40
Duplicate of https://github.com/mxrch/GHunt/issues/304.

**Closed by mxrch** 2022-06-04 10:40 UTC
