### ISSUE TITLE
Got a question

### ISSUE THREAD

**Issue by XFORWORKS** [mxrch/GHunt#468] opened 2023-11-12 16:02 UTC
What exactly was changed in 2.0.4? I can't look in the files, and I need to because I'm using a modified ver of GHunt which has this bug from 2.0.3 :
```
[+] Authenticated !
Traceback (most recent call last):
  File "/home/retr0/.local/bin/ghunt", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/retr0/.local/lib/python3.11/site-packages/ghunt/ghunt.py", line 15, in main
    parse_and_run()
  File "/home/retr0/.local/lib/python3.11/site-packages/ghunt/cli.py", line 31, in parse_and_run
    process_args(args)
  File "/home/retr0/.local/lib/python3.11/site-packages/ghunt/cli.py", line 41, in process_args
    trio.run(email.hunt, None, args.email_address, args.json)
  File "/home/retr0/.local/lib/python3.11/site-packages/trio/_core/_run.py", line 1946, in run
    raise runner.main_task_outcome.error
  File "/home/retr0/.local/lib/python3.11/site-packages/ghunt/modules/email.py", line 31, in hunt
    is_found, target = await people_pa.people_lookup(as_client, email_address, params_template="max_details")
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/retr0/.local/lib/python3.11/site-packages/ghunt/apis/peoplepa.py", line 103, in people_lookup
    person_data = list(data["people"].values())[0]
                       ~~~~^^^^^^^^^^
KeyError: 'people'
```
Since I'm using a modified version, I must manually change the problematic line.

**Comment by ranlo** [comment] 2023-11-13 06:36
This seems like a duplicate of https://github.com/mxrch/GHunt/issues/467

I think the issue is on due to a change on Google's side. My version stopped working all of a sudden, without any change on the GHunt side

**Comment by XFORWORKS** [comment] 2023-11-13 12:09
Appreciate it.

**Closed** 2023-11-13 12:09 UTC

**Comment by XFORWORKS** [comment] 2023-11-13 12:22
Nevermind,still doesn't work.

**Comment by XFORWORKS** [comment] 2023-11-13 12:23
@mxrch
