### ISSUE TITLE
Stuck on "Got the albums overview !"

### ISSUE THREAD

**Issue by panagiac** [mxrch/GHunt#13] opened 2020-10-03 16:54 UTC
`Traceback (most recent call last):
  File "hunt.py", line 114, in <module>
    gpics(gaiaID, client, cookies, cfg)
  File "___\photos.py", line 97, in gpics
    out = get_source(gaiaID, client, cookies, cfg)
  File "___\lib\photos.py", line 82, in get_source
    result = wait.until(element_has_substring_or_substring((By.XPATH, "//body"), photos_trigger, no_photos_trigger))
  File "___\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:`

**Comment by mxrch** [comment] 2020-10-03 17:00
Hello @panagiac , it's a duplicate of the issue https://github.com/mxrch/GHunt/issues/10
I invite you to come on it and do the same thing I asked for the other person, to get a debug.html.
I close this issue to keep issues clean !

**Closed** 2020-10-03 17:01 UTC
Labels: duplicate
