### ISSUE TITLE
docker build fails due to chrome version

### ISSUE THREAD

**Issue by kirinnee** [mxrch/GHunt#68] opened 2020-10-08 08:44 UTC
Dockerfile
```
ENV CHROMEDRIVER_VERSION 85.0.4183.87
ENV CHROME_VERSION 85.0.4183.121-1
```

Error Logs:
```
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK
Get:1 http://dl.google.com/linux/chrome/deb stable InRelease [1811 B]
Hit:2 http://security.debian.org/debian-security buster/updates InRelease
Hit:3 http://deb.debian.org/debian buster InRelease
Get:4 http://dl.google.com/linux/chrome/deb stable/main amd64 Packages [1074 B]
Hit:5 http://deb.debian.org/debian buster-updates InRelease
Fetched 2885 B in 1s (5476 B/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Version '85.0.4183.121-1' for 'google-chrome-stable' was not found
The command '/bin/sh -c groupadd -g ${GID} -r app && adduser --system --home /home/app --ingroup app --uid ${UID} app &&     chown -R app:app /usr/src/app &&     apt-get update &&     apt-get install -y curl unzip gnupg &&     curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - &&     echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list &&     apt-get update &&     apt-get install -y google-chrome-stable=${CHROME_VERSION} &&     rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by zefj** [comment] 2020-10-08 09:01
@kirinnee changing `CHROME_VERSION` to `86.0.4240.75-1` worked for me

**Comment by JuliaCao** [comment] 2020-10-08 16:44
duplicate of #58

**Closed** 2020-10-08 22:49 UTC
