### ISSUE TITLE
Error in check_and_gen.py

### ISSUE THREAD

**Issue by Chrisfranco01** [mxrch/GHunt#346] opened 2022-06-03 15:16 UTC
error in check_and_gen.py

![Screenshot_2](https://user-images.githubusercontent.com/61951238/171882739-bde2ce70-4a0e-460d-8038-7302206931d8.png)

 - Windows 10 64bits
 - Python 3.10.4

**Comment by hackerkartel64** [comment] 2022-06-04 08:51
i have this problem in kali too. Is anyone gonna provide a solution for us ??

**Comment by mxrch** [comment] 2022-06-04 10:41
Duplicate of https://github.com/mxrch/GHunt/issues/304.

**Closed by mxrch** 2022-06-04 10:41 UTC

**Comment by hackerkartel64** [comment] 2022-06-04 14:11
mxrch the best
