### ISSUE TITLE
TypeError: quote_from_bytes() expected bytes

### ISSUE THREAD

**Issue by ashan890** [mxrch/GHunt#164] opened 2020-11-26 16:39 UTC
[+] Activated Google services :
- Kaboo
- Maps
Traceback (most recent call last):
  File "C:\Users\Hp\Desktop\GHunt\hunt.py", line 132, in <module>
    data = ytb.get_channels(client, name, config.data_path,
  File "C:\Users\Hp\Desktop\GHunt\lib\youtube.py", line 86, in get_channels
    from_youtube = youtube_channel_search(client, query)
  File "C:\Users\Hp\Desktop\GHunt\lib\youtube.py", line 14, in youtube_channel_search
    req = client.get(link.format(urllib.parse.quote(query)))
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\urllib\parse.py", line 853, in quote
    return quote_from_bytes(string, safe)
  File "C:\Users\Hp\AppData\Local\Programs\Python\Python39\lib\urllib\parse.py", line 878, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes

**Comment by ashan890** [comment] 2020-11-27 08:12
Anyone have a solution for this ?🤔

**Comment by mxrch** [comment] 2020-11-27 12:01
@ashan890 duplicate of https://github.com/mxrch/GHunt/issues/163.

**Closed by mxrch** 2020-11-27 12:01 UTC
