### ISSUE TITLE
Seems like the cookies are invalid, try regenerating them.

### ISSUE THREAD

**Issue by QueenBytes** [mxrch/GHunt#373] opened 2022-11-09 21:24 UTC
Getting an error trying to load cookies.
I have cleared cache, signed out and back in, tried a different browser, manually loaded them, base64 loaded them, used the sync option.
no matter what i do i get the same error
"Seems like the cookies are invalid, try regenerating them."
Please help!!!

I also uninstalled and reinstalled ghunt

**Comment by roseninc** [comment] 2022-11-10 14:37
Having the same issue here

**Comment by dennixone** [comment] 2022-11-11 14:29
me 2 same issue

**Comment by hostile-gabriel** [comment] 2022-11-12 14:53
Having the same issue, please fix!

**Comment by mxrch** [comment] 2022-11-12 23:19
> *please fix*

not motivated, do it yourself

**Comment by Ruane-Corteze** [comment] 2022-11-13 14:58
me too i have the same problem. how i can fix it

**Comment by perturbatorx** [comment] 2022-11-14 11:38
The issue is from my own experience pertaining to the LSID cookie - a cookie that is basically not available any longer. Cookies are generally becoming more difficult to view and access just by "browsing" in your own system. On some browsers the data is simply not viewable in Explorer etc. 

I downloaded Chromium on a Linux system and the LSID cookie was viewable and it was possible to extract the data from it however this does not resolve the issue. I have not had the chance to analyze fully yet, but most likely it is a google issue and not a script issue. Perhaps @mxrch knows more, but it seems like google is closing down.

**Comment by mxrch** [comment] 2022-11-23 20:45
Should be fixed in https://github.com/mxrch/GHunt/pull/384.

**Closed by mxrch** 2022-11-23 20:45 UTC

**Comment by My5t-404** [comment] 2023-08-30 20:15
I have been facing the same issue now. what is the solution?
