### ISSUE TITLE
AttributeError: 'JpegImageFile' object has no attribute 'getexif'

### ISSUE THREAD

**Issue by com0t** [mxrch/GHunt#60] opened 2020-10-07 09:45 UTC
i was install requirements.txt

**Comment by PinkDev1** [comment] 2020-10-07 14:58
Post the full error message, the command you ran, and your python version; Otherwise we can't help you

Due to vagueness, this might just be a duplicate of #54

**Comment by mxrch** [comment] 2020-10-07 22:23
So you got an AttributeError when installing the requirements.txt ? 🤔 
Please help us understand by doing what PinkDev1 said.

**Closed** 2020-10-09 12:40 UTC
